query {
  articles {
    data {
      id
      attributes {
        name
        description
        images 
        category {
          data {
            attributes {
              name
            }
          }
        }
      }
    }
  }
}
